AliceO2Group/WebUi

- InfoLogger/lib/configProvider.js
This fixes the problem with writing logs to the file.
> Pass configuration parameters to logging class

- Control/protobuf/o2control.proto
- Control/public/common/showTableItem.js
Control status page is displaying all information sent back by the `getFrameworkInfo` request. 
Modified table to display JSON object if present instead of expected value. (e.g. version field). Otherwise it would have displayed an empty field
> OGUI-277 display user friendly instance name

- QualityControl/public/object/Object.js
In case an object is not found or the server is not able to parse the JSON then the user should know about it.
> [OGUI-318] Inform user for issues reading Object

- InfoLogger/package-lock.json
- InfoLogger/package.json
Seems like even 1.1.3 was removed we cannot use that version anymore in npm artifactory.
> Bump infologger version to 1.1.5

- Control/public/common/showTableList.js
- Control/public/environment/Environment.js
- Control/public/environment/environmentPage.js
- Control/public/environment/environmentsPage.js
Changes in PR:
* `Delete` button from environment page was removed
* A `Shut Down` button was added in the environments page table
* User will be asked to confirm shutting down the environment
* In case state is not `locked` a danger notification(5s) will be displayed  when user tries to shut down the environment
> [OGUI-352] Move shutdown option to all envs page

- InfoLogger/public/logFilter/tableFilters.js
When there are no Error/Fatal errors and the user would use arrows to navigate through the logs then a notification would be displayed informing the user there are no such logs.
Bug fixed where this would happen even when the user would use the arrows within the input fields.
> [OGUI-379] Stop keydown event propagating out of input fields

- Control/public/environment/environmentPage.js
In case aliecs did not manage/have enough time to get the data about where plots are hosted, a message will be displayed to the user.
> [OGUI-378] Inform user when plots were not loaded

- .travis.yml
- QualityControl/public/object/objectDraw.js
- QualityControl/public/object/objectPropertiesSidebar.js
To force JSROOT to look at all stats options from the canvas, "stats" and "nostats" need to be provided as options rather than "stat"
> [OGUI-297] stat does not seem to work

- .codecov.yml
- .github/workflows/qc.yml
Issues: 
* Our npm coverage is failing on Ubuntu due to known JS out of memory issue and that is why coverage was moved to MacOS
* CodeCov - GH ACtion is not yet supported on MacOS https://github.com/codecov/codecov-action/issues/13 and that is why codecov was removed. Bash is supported and also faster.
> [OGUI-416] Run coverage on macos for QCG

- Control/lib/api.js
Select only `hostname` and `port` from `http` configuration so that certificates and keys are not displayed
> [OGUI-256] Do not add all config options

- QualityControl/lib/QCModelDemo.js
- QualityControl/package.json
- QualityControl/public/Model.js
- QualityControl/public/layout/Layout.js
- QualityControl/public/layout/layoutShowPage.js
- QualityControl/public/object/QCObject.js
- QualityControl/public/object/view/objectViewPage.js
- QualityControl/public/services/Layout.service.js
- QualityControl/public/view.js
- QualityControl/test/public/mocha-index.js
objecView page should:
* display an object with default options (set in C++) if it was called from objectTree page; (URL is based on objectName)
For below scenarios URL will be based on layoutId and objectId; If one of them is missing an error icon will be displayed;
* display an object with both default and layout options merged if it is called from layoutShow page
* display an object with only the layout options if it is called from layoutShow page and the user selected "Ignore defaults" for that object in layoutEdit mode
e.g of objects that can be used to test: objectName=qc/testOptions/colz_arr
> [OGUI-391] Object view drawing options layout should be propagated 

- InfoLogger/lib/SQLDataSource.js
- InfoLogger/test/lib/mocha-sqldatasource.js
If SQLDataSource is unable to query, rather than returning empty (which might confuse the user thinking there are no logs for their criteria/filters), an error will be thrown.
> [OGUI-466] Throw error if unable to query

- QualityControl/config-default.js
Pointed out in https://alice-talk.web.cern.ch/t/qc-task-error-servicediscovery-timeout-was-reached/505/3 by Stefan.
> Fix a hostname typo in config-default.js

- Framework/Backend/http/server.js
- Framework/Backend/test/mocha-http.js
- Framework/Backend/test/mocha-ws.js
- Framework/docs/guide/http-server.md
- Framework/package-lock.json
- Framework/package.json
This change allows for more freedom over starting/stopping of the server. It is however breaking for any applications currently using WebUI!
Reason for this change is that it allows us to configure the server before starting it. This also allows us to wait for the database to be up and running before starting the web server. Simplifies graceful shutdown as we do not need to access the underlying server layer. It also simplifies the testing with supertest.
> Added listen, close and address method

- Framework/Backend/http/server.js
- Framework/Backend/test/mocha-http.js
Added an error handler for routes/controllers on the `/api` router. The response should be JSON not HTML and based on the NODE_ENV the error message should be included. Chosen for the explicit `development` instead of the not `production` statement to be backwards compatible.
---
> Added API error handler

- QualityControl/config-default.js
- QualityControl/lib/CCDBConnector.js
- QualityControl/lib/QCModel.js
- QualityControl/lib/QCModelDemo.js
- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/public/object/ObjectTree.class.js
- QualityControl/test/lib/mocha-ccdb-connector.js
- QualityControl/test/public/mocha-index.js
- QualityControl/test/test-config.js
PR which includes:
* An updated version of the CCDBConnector to include a prefix taken from the configuration file. This prefix shall be used in all queries to CCDB
* Tests for CCDB old and new functionality
* Updated header in CCDBConnector to make use of the new functionality in which we can specify which fields should be sent back
> [OGUI-550] && [OGUI-547] Use prefix on ccdb queries

- .gitignore
- Control/test/integration/control-environment.js
- Control/test/integration/core-tests.js
- Control/test/integration/create-new-environment.js
Improve current integration-tests:
* take name of workflow to be tested and timeout allowed for core requests from test-config file if it exists otherwise use defaults; [OGUI-570]
* Check for `itemControl` in tests controlling the environment. This will give a proper message in case an action will fail [OGUI-569]
* Added 5s sleep before actions "RESET" and "SHUTDOWN". This is a temporary fix needed for [OCTRL-232]
> [OGUI-570] & [OGUI-569] Improve integration-tests

- Control/package-lock.json
- Control/package.json
- Control/public/workflow/workflowsPage.js
Add a small info icon (temporarily) to redirect user to the link with documentation on KV environments panel. 
On hover inform the user.
> [OGUI-571] Add info icon on KV env panel

- Framework/Backend/http/server.js
- Framework/Backend/test/mocha-http.js
The current JWT error response does not explain to the end user why their request has failed. The proposed implementation uses the error message of the JWT package to atleast give a hint.
```json
{
"message": "JsonWebTokenError"
}
```
```json
{
"error": "403 - Json Web Token Error",
"message": "You must provide a JWT token"
}
```
```json
{
"message": "JsonWebTokenError"
}
```
```json
{
"error": "403 - Json Web Token Error",
"message": "Invalid JWT token provided"
}
```
> [OGUI-575] Include a message why the JWT failed

- Control/lib/ConsulConnector.js
- Control/test/lib/mocha-consul-connector.js
In order to prevent potential issues when Ansible creates keys in Consul KV Store with empty values, we should use a set to remove duplicate keys
> [OGUI-577] Use set for Consul Keys

- Framework/Frontend/js/src/renderer.js
Free console resources even if the render throws an error. Currently, the timer will keep running on the background, calling `console.time('render');` won't restart the timer but display a warning (and thus keeps the existing time). This fix will always stop and clear the timer.
> Free console resources even if the render failed

- Control/package-lock.json
- Control/package.json
- Control/public/environment/environmentPage.js
Button state was changed to a `display:none` rather than entirely removed so that it can still be used within the FLP Integration Tests
> [OGUI-612] hide shutdown button

- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/public/object/ObjectTree.class.js
- QualityControl/public/object/objectTreePage.js
- QualityControl/public/object/objectTreeSidebar.js
PR tackles the bug raised on ALICE Talk blog: https://alice-talk.web.cern.ch/t/check-policy-oneachseparately/639 
QCG will not create a folder for objects if there is an object already with the same path
E.g:
```
qc/TST/PiotrTest/histo/histo1
qc/TST/PiotrTest/histo/histo2
qc/TST/PiotrTest/histo
```
would result in only `qc/TST/PiotrTest/histo` to be displayed. 
PR also removes the deprecated `quality` column from the object tree
> [OGUI-628] Allow objects with same name as sub-path

- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/test/integration/offline-mode.js
- QualityControl/test/integration/online-mode.js
Add half a second before and after opening JSRoot plot to allow for rendering to be completed before checking if it was opened successfully .
> [OGUI-629] Add waiting rendering time

- QualityControl/lib/CCDBConnector.js
- QualityControl/lib/QCModel.js
- QualityControl/lib/QCModelDemo.js
- QualityControl/lib/TObject2JsonClient.js
- QualityControl/lib/api.js
- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/public/app.css
- QualityControl/public/common/infoButton.js
- QualityControl/public/common/timestampSelectForm.js
- QualityControl/public/object/QCObject.js
- QualityControl/public/object/objectDraw.js
- QualityControl/public/object/objectTreePage.js
- QualityControl/public/object/view/objectViewPage.js
- QualityControl/public/services/QCObject.service.js
- QualityControl/test/lib/mocha-ccdb-connector.js
- QualityControl/test/public/mocha-index.js
- QualityControl/tobject2json.cc
**Acceptance Criteria:**
History of a timestamp feature is present on pages `objectTree` and `objectView`.  
For both pages:
* Select an object to display (e.g  `qc/TST/External-1/hello_0`)
* Click `i` (info) button to see last modified timestamp
* Ensure last modified timestamp from info panel is the same as the timestamp from the dropdown
* Select a different timestamp (preferably a few hours older so that plot difference it's easily seen) from the dropdown (bottom in the `objectTree` page and top for `objectView`)
* Ensure plot changed
* Ensure  info panel still displays the correct last modified timestamp. It  should not change
* Select a different object (this will request latest information of the object)
* Ensure last modified timestamp from info panel is the same as the timestamp …
> [OGUI-330] navigate object timestamp history
