AliceO2Group/WebUi

- docs/API.md
- http/server.js
- test/mocha-http.js
Added two methods: get and getNoAuth.
Updated doc.
Added tests.
> Ogui-106 get method

- http/oauth.js
- http/server.js
- package-lock.json
- package.json
https://alice.its.cern.ch/jira/browse/OGUI-123
This allows to refresh page as long as the JWT token is valid.
> Remove server-side template engine and pass parameters in the URL

- .travis.yml
- http/server.js
- jwt/token.js
- public/websocket-client.js
- test/travis-mocha-ws.js
- websocket/server.js
https://alice.its.cern.ch/jira/projects/OGUI/issues/OGUI-102
https://alice.its.cern.ch/jira/projects/OGUI/issues/OGUI-125
> Drop WebSocket OAuth and token refresh

- config-default.json
- package-lock.json
- package.json
- test/mocha-http.js
- test/travis-mocha-ws.js
https://alice.its.cern.ch/jira/browse/OGUI-126
> Remove chai from tests

- .eslintrc.js
- http/server.js
- package-lock.json
- package.json
Removed:
- eslint-plugin-security		
- nsp
- phantom	
- qunit
- qunit-phantomjs-runner
- jquery
- compression
- body-parser
> Remove unused deps

- Backend/http/server.js
- Backend/jwt/token.js
- Backend/test/mocha-http.js
As requested in https://github.com/AliceO2Group/Gui/pull/75
> Support flow without OAuth

- QualityControl/README.md
- QualityControl/package.json
> Improve QC docs

- QualityControl/public/app/Model.js
- QualityControl/public/app/QueryRouter.class.js
- QualityControl/public/app/object/Object.js
- QualityControl/public/app/object/objectTree.js
- QualityControl/public/app/sidebar.js
- QualityControl/public/app/view.js
+ fix Object name
+ fix const assignement twice
> Changed router properties access

- Framework/Backend/http/server.js
- Framework/Backend/test/mocha-http.js
- Framework/Frontend/js/lib/mithril.js
- Framework/Frontend/js/src/index.js
- Framework/Frontend/js/src/renderer.js
- Framework/Frontend/test/mocha-index.js
- Framework/package-lock.json
- Framework/package.json
includes Mithril as lib instead of package
> Remake frontend tests without Babel 

- Framework/Frontend/css/src/bootstrap.css
- Framework/Frontend/js/src/Loader.js
- Framework/Frontend/test/mocha-index.js
- Framework/docs/reference/frontend-api.md
- Framework/docs/reference/frontend-css.html
- Framework/package-lock.json
- Framework/package.json
- InfoLogger/package-lock.json
- InfoLogger/package.json
- InfoLogger/public/app.css
- QualityControl/package-lock.json
- QualityControl/package.json
- Management of GET request by Loader
- Buttons from ILG
- font size 7
- color green for validated states
> Improvements to CSS and loader

- Framework/Backend/zeromq/client.js
When connecting and disconnecting hostname was not displayed properly...
> Fix ZMQ log messages

- Framework/Backend/websocket/server.js
- Framework/package-lock.json
- Framework/package.json
- InfoLogger/package-lock.json
- InfoLogger/package.json
- InfoLogger/public/Model.js
- InfoLogger/public/common/Timezone.js
- InfoLogger/public/logFilter/LogFilter.js
- framework error handling for broadcast filtering (patch 1.3.1, published)
- ILG fix filter error
- ILG fix momentJS deprecation
> Improve error handling

- Control/package-lock.json
- Control/package.json
- Control/public/Model.js
- Control/public/common/appHeader.js
- Framework/Frontend/css/src/bootstrap.css
- Framework/docs/reference/frontend-css.html
- Framework/package-lock.json
- Framework/package.json
- InfoLogger/package-lock.json
- InfoLogger/package.json
- InfoLogger/public/Model.js
- InfoLogger/public/log/commandLogs.js
- InfoLogger/public/view.js
- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/public/Model.js
- QualityControl/public/common/header.js
- Added logged user to apps
- Added dropdown menu to framework
> Display details of a currently logged user

- Framework/Frontend/css/src/bootstrap.css
- QualityControl/public/common/sidebar.js
- QualityControl/public/layout/layoutShowHeader.js
> OGUI-248 Glitch with long layout names

- Framework/package-lock.json
- Framework/package.json
Small PR for increasing the version of Framework for release
> [OGUI-248] Bump version for Framework

- Framework/Frontend/css/src/bootstrap.css
- Framework/docs/reference/frontend-css.html
- Framework/package-lock.json
- Framework/package.json
Updates on framework:
* add new width option(75%) 
* fix a bug in which icons where not inheriting colour of the parent due to variable being declared as string rather than variable
* bumping version as well for release
> OGUI-255 add new width option and fix icons

- Control/lib/api.js
- Control/public/common/showTableItem.js
- Control/public/common/showTableList.js
- Control/public/common/utils.js
PR which includes:
* dealing special cases to display needed information. These tables will be modified based on future requirements. 
* Special case to deal with uint64 which JSON cannot understand. To use String in the future.
> OGUI-280 Framework Table

- InfoLogger/package-lock.json
- InfoLogger/package.json
Version bump needed for Ansible Recipe
> [OGUI-308] Bump version

- QualityControl/public/object/Object.js
In case server cannot parse JSON due to error, user should be informed:
> [OGUI-295] Add notification in case of error on list request

- Framework/Frontend/css/src/bootstrap.css
- Framework/docs/reference/frontend-css.html
- Framework/package-lock.json
- Framework/package.json
* Bump version for release
* Added success-button 
* Release is needed mostly for fixing bug of ```Log.Trace```
> [OGUI-326] Update buttons + Bump version for release

- Control/lib/ControlProxy.js
- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/app.css
- Control/public/common/appHeader.js
- Control/public/common/pageLoading.js
- Control/public/environment/environmentsPage.js
- Control/public/status/statusPage.js
- Control/public/workflow/workflowsPage.js
Changes: 
* In case GRPC has a connection error, requests will not wait for response but will send back a 504 status and messsage "GRPC module is not connected"
* Loading/Error Pages have been updated
**PR Should be updated and merged only after web-ui is released with the fix of ```Log.trace```** (https://github.com/AliceO2Group/WebUi/pull/302)
> [OGUI-310] Notify user when GRPC not available

- InfoLogger/package-lock.json
- InfoLogger/package.json
- InfoLogger/public/logFilter/commandFilters.js
* Devel log level display messages with level set to NULL
> Bump InfoLogger to 1.1.2

- Control/public/Model.js
- Control/test/mocha-index.js
Change default home-page to "Environments" section rather than "Status"
> [OGUI-335] Change default home-page

- Framework/Frontend/css/src/bootstrap.css
- Framework/docs/reference/frontend-css.html
- Framework/package-lock.json
- Framework/package.json
PR to add badge class(to be used for making run number more visible), update documentation with warning buttons theme and bump version
> [OGUI-332] Add badge class and bump version

- Control/config-default.js
- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/common/showTableList.js
- Control/public/environment/Environment.js
- Control/public/environment/environmentPage.js
- Control/test/mocha-index.js
- Framework/Backend/http/server.js
- Framework/Frontend/css/src/bootstrap.css
- Framework/docs/reference/frontend-css.html
- Framework/package-lock.json
- Framework/package.json
- QualityControl/public/Model.js
- QualityControl/test/mocha-index.js
PR fo realeasing @aliceo2/web-ui@1.8.9
> WebUI Bump Version

- Control/lib/api.js
Added a new http request which will check the health of the grafana node:
* status 200 from healthcheck -> list of plots to be displayed will be sent to the UI
* In case of error, a 504 response will be sent to the UI and no plots will be displayed
> [OGUI-302] Check if grafana is healthy in api

- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/common/showTableList.js
- Control/public/environment/environmentPage.js
Release Notes - O2 GUI - Version @aliceo2/control@1.1.1
<h2>        New Feature
</h2>
<ul>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-302'>OGUI-302</a>] -         Embed plots from Grafana into Control GUI
</li>
</ul>
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-332'>OGUI-332</a>] -         Make run number more visible
</li>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-333'>OGUI-333</a>] -         Use color scheme for the states
</li>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-348'>OGUI-348</a>] -         Apply color scheme for the tasks state
</li>
</ul>
> @aliceo2/control@1.1.1

- QualityControl/package-lock.json
- QualityControl/package.json
* Did not encounter any issues/warnings/errors after the version bump. 
* Objects seem to be displayed as normal.
* Bump did not fix the "Legend dissapearing" / "Stat missing" problem of redrawing.
> [OGUI-339] Test new JSRoot 5.7.0

- Control/lib/api.js
- Control/public/environment/environmentPage.js
* Display grafana only if state is RUNNING
* Refresh grafana plots every 5s
> [OGUI-353] Grafana panels improvements

- Control/public/app.css
- Control/public/environment/environmentPage.js
> [OGUI-280] Increase run number display

- .travis.yml
- Control/lib/api.js
- Control/public/app.css
- Control/public/common/showTableList.js
- Control/public/environment/Environment.js
- Control/public/environment/environmentPage.js
- Control/public/environment/environmentsPage.js
- QualityControl/package-lock.json
- QualityControl/package.json
Release Notes - O2 GUI - Version @aliceo2/control@1.1.2
<h2>        Improvement
</h2>
<ul>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-280'>OGUI-280</a>] -         Display run number
</li>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-352'>OGUI-352</a>] -         Improve &quot;delete/trash&quot; environment button
</li>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-353'>OGUI-353</a>] -         Grafana panels improvements
</li>
</ul>
> @aliceo2/control@1.1.2

- Framework/Frontend/js/src/BrowserStorage.js
- Framework/Frontend/js/src/index.js
- Framework/Frontend/test/mocha-index.js
- Framework/package-lock.json
- Framework/package.json
* Added BrowserStorage class which purpose is to encapsulate localStorage and sessionStorage. This will help in reducing the number of HTTP requests 
* Version minor bump
> [OGUI-361] Add BrowserStorage class

- Control/config-default.js
- Control/index.js
- Control/lib/KafkaConnector.js
- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/Model.js
- Control/test/mocha-kafka-connector.js
- Control/test/test-config.js
- Framework/Frontend/js/src/BrowserStorage.js
- Framework/Frontend/js/src/index.js
- Framework/Frontend/test/mocha-index.js
- Framework/package-lock.json
- Framework/package.json
Release Notes - O2 GUI - Version @aliceo2/web-ui@1.9.0
<h2>        New Feature
</h2>
<ul>
<li>[<a href='https://alice.its.cern.ch/jira/browse/OGUI-361'>OGUI-361</a>] -         Add Session &amp; Local Storage
</li>
</ul>
> @aliceo2/web-ui@1.9.0

- InfoLogger/public/logFilter/LogFilter.js
- InfoLogger/public/logFilter/tableFilters.js
- InfoLogger/test/mocha-index.js
Based on feedback from users #354 
Also, fixes the filtering based on SQL Wildcards in Live Mode
> [OGUI-371] On focusout should reset criteria

- .travis.yml
- InfoLogger/package-lock.json
- InfoLogger/package.json
- InfoLogger/public/Model.js
- InfoLogger/public/app.css
- InfoLogger/public/log/Log.js
- InfoLogger/public/log/tableLogsScrollMap.js
- InfoLogger/public/logFilter/LogFilter.js
- InfoLogger/public/logFilter/commandFilters.js
- InfoLogger/public/logFilter/tableFilters.js
- InfoLogger/public/view.js
While in Query Mode, if the users updates the filters, a standard ALICE notification will be displayed(2s) to inform the user that in order to get the results based on the new criteria he will need to press the Query button again. 
While in PAUSE Online mode, modifying the filters will not result in a notification being displayed.
While in RUN Online mode, the same ALICE notification will be displayed to notify the users that filters have been updated. 
While input fields are focused, arrows events will be ignored. Clicking outside of the input fields (table or above) will re-enable them.
> [OGUI-376] Notify users to requery if filters have been changed

- InfoLogger/package-lock.json
- InfoLogger/package.json
- InfoLogger/public/log/statusBar.js
> [OGUI-377] Suggest user there are more messages

- QualityControl/lib/api.js
- QualityControl/package-lock.json
Fix bug in which online mode was queried even if no configuration was provided
> [OGUI-386] Fix model is not function

- QualityControl/public/app.css
- QualityControl/public/layout/layoutShowPage.js
- QualityControl/public/object/objectTreePage.js
- QualityControl/public/object/objectTreeSidebar.js
Objects in the tree page/tree sidebar should hint the user they can be selected
> [OGUI-384] Selectable objects should be highlighted

- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/public/common/sidebar.js
- QualityControl/public/layout/layoutShowHeader.js
- QualityControl/public/object/QCObject.js
- QualityControl/public/object/objectTreePage.js
- QualityControl/test/public/mocha-index.js
> [OGUI-327] Search in tree is broken

- Control/package-lock.json
- Control/package.json
- Control/protobuf/o2control.proto
- Control/public/environment/newEnvironmentPage.js
- Control/public/workflow/workflowsPage.js
* Update proto file
* Update workflow page according to the new API response
* Bump version to 1.3.0
> [OGUI-392] Update based on new API response

- Control/package-lock.json
- Control/package.json
- Control/public/common/showTableList.js
- Control/public/environment/environmentPage.js
- Control/public/environment/environmentsPage.js
Add horizontal scrollbar for tables in EnvironmentPage && EnvironmentsPage so that users can access the actions column when using a screen smaller than the content of the table
Fix bug in which CSS for the row was not applied to Actions cell due to btn-group class
> [OGUI-402] Add horizontal scroll bar table

- Control/config-default.js
- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/Model.js
- Control/public/app.css
- Control/public/common/sidebar.js
- Control/public/configuration/Configuration.js
- Control/public/configuration/configurationPage.js
- Control/public/view.js
- Control/test/lib/mocha-kafka-connector.js
- Control/test/test-config.js
- Framework/package-lock.json
In order to test it please fill in your config.js file with details about consul as per the config-default.js file in this PR
> [OGUI-460] Display CRUs table && [OGUI-461] Enable CRUs selection

- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/configuration/configurationPage.js
If there is no key found in Consul based on the control configuration then a 404 error message will be displayed as below: 
If there are no values associated to the key provided in the control configuration than the table will contain a single row specifying there was no data found as per the screenshot below:
> [OGUI-473] Message for missing key or data in configuration

- Control/public/workflow/Workflow.js
- Control/test/public/page-new-environment-mocha.js
When the user requests to ask core for a refresh, UI should request for the repositories contents to be renewed as well
> [OGUI-482] On refresh get contents as well

- QualityControl/README.md
The important piece is the updated path to `config.js`.
> Update doc, fix the path to config.js

- QualityControl/package.json
- QualityControl/public/common/header.js
- QualityControl/public/object/QCObject.js
- QualityControl/public/object/objectTreePage.js
- QualityControl/test/public/mocha-index.js
* Initial calls to fill in ObjectTree page duplicated oncreation now fixed
* User will not allowed to Query online mode while offline is already querying and vice versa so that trees are not overwritten one by another
> [OGUI-470] &  [OGUI-469]

- QualityControl/README.md
- QualityControl/config-default.js
- QualityControl/lib/QCModel.js
As this is a markdown change, it will be easier to review if you are looking straight to the documentation from the branch itself: 
https://github.com/AliceO2Group/WebUi/tree/doc/QCG/OGUI-501-update-consul-docs/QualityControl
> [OGUI-501] Update documentaiton on Consul

- Framework/Backend/http/server.js
- Framework/package-lock.json
- Framework/package.json
Just need to make sure that passing attaching token and user information to `req` does not introduce any flows? Where the call goes after calling `next()` ?
> [OGUI-517] Fix UnhandledPromiseRejection in HTTP module

- Control/public/Model.js
- Control/public/app.css
- Control/public/common/errorComponent.js
- Control/public/common/errorPage.js
- Control/public/configuration/Configuration.js
- Control/public/configuration/configurationPage.js
- Control/public/environment/environmentPage.js
- Control/public/environment/environmentsPage.js
- Control/public/frameworkinfo/frameworkInfoPage.js
- Control/public/workflow/Workflow.js
- Control/public/workflow/revisionPanel.js
- Control/public/workflow/workflowsPage.js
- Control/test/public/page-configuration-mocha.js
- Control/test/public/page-new-environment-mocha.js
Testing: 
Case 1:
Version of AliECS core: `0.12.90`
Use coconut to add a new repository: `coconut repo add <repo_link>`
Change default revision to first repository: `coconut repo default-revision 0 basic-tasks`
Check that UI displays `basic-tasks` as revision when "newEnvironment" page loads
Case 2:
Ensure compatibility with prior versions <= `0.12.2`
> [OGUI-498] use revision default configuration

- Framework/Frontend/js/src/compatibility.js
- Framework/README.md
- Framework/package-lock.json
- Framework/package.json
The old version of edge is placed in userAgent as "edge" while the new one based on Chromium is labeled as "edg"
> [OGUI-518] update browser version edge

- Control/package-lock.json
- Control/package.json
- Control/public/app.css
- Control/public/common/showTableList.js
- Control/public/common/sidebar.js
- Control/public/environment/environmentPage.js
- Control/public/workflow/Workflow.js
- Control/public/workflow/revisionPanel.js
- Control/public/workflow/workflowsPage.js
- Control/test/public/page-new-environment-mocha.js
PR which will add an extra panel for the users to fill in their (K;V) variables;
Conditions: 
* If Key or Value input fields are empty the user will be prompted with a red notification and pair will not be added
* After adding a variable pair, if the user tries to empty the value of an existing pair a warning will be displayed and initial value filled back in
* `environmentsPage` will not display in the table the variables
* `environmentPage` will display in its table the variables
> [OGUI-524] new env k v panel

- Framework/Backend/http/server.js
- Framework/Backend/test/mocha-http.js
Currently the framework does not support middleware, this is **one** implementation to support it.
> [OGUI-534] Support multiple express middlewares per route

- Control/lib/api.js
- Control/package-lock.json
- Control/package.json
- Control/public/workflow/flpSelectionPanel.js
- Control/test/lib/mocha-consul-connector.js
* If Consul returns 404 for not finding Key, print special message to the user so that they are not confused if Consul is running or not
* Fix small bug in which `flpHardwarePaths` was not passed to connector
> [OGUI-539] Inform user on missing key

- Control/public/workflow/revisionPanel.js
- Control/public/workflow/workflowsPage.js
Change the event listeners for `input fields` from `onkeyup` to `oninput` to include paste events from the mouse/trackpad as well
> [OGUI-562] Change from key to input listener 

- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/public/object/QCObject.js
- QualityControl/test/public/mocha-index.js
CCDB removed sorting of objects in their request and asked clients of their API to deal with the sorting.
> [OGUI-563] Sort initial request from ccdb

- InfoLogger/package-lock.json
- InfoLogger/package.json
Bump version patch of ILG to include dependency version upgrades to remove vulnerabilities spotted by GH Scan
> [OGUI-556] Bump ILG version patch

- Framework/Backend/http/server.js
- Framework/package.json
Replace the explict `body-parser` dependency with the built-in parser of Express.
> [OGUI-576] Use the built-in middleware function for parsing JSON payloads

- Control/package-lock.json
- Control/package.json
- Control/public/environment/environmentPage.js
> [OGUI-583] Add force shutdown button

- Framework/package-lock.json
- Framework/package.json
https://github.com/winstonjs/winston/issues/1818
> [OGUI-596] Use fix winston version

- .github/workflows/control.yml
- Control/package-lock.json
- Control/package.json
Bump AliECS GUI for release to 1.6.6
Bump Framework version
Update GH Action to NodeJS 14 to see if node-grpc bug is fixed.
> Bump aliecs GUI 1.6.6

- InfoLogger/public/Model.js
- InfoLogger/public/logFilter/LogFilter.js
- InfoLogger/test/mocha-index.js
- [x ] branch and/or PR name(s) includes JIRA ID
- [x ] issue "Status" is set to "In review"
- [x ] PR labels are selected
> [OGUI-585] Filters set by url with profile

- .github/workflows/framework.yml
- Framework/Frontend/js/src/renderer.js
Fix for: https://github.com/AliceO2Group/WebUi/pull/555
> Fix Lint issue

- Control/package-lock.json
- Control/package.json
- Control/public/workflow/Workflow.js
> [OGUI-609] keep form data new env

- Control/public/environment/environmentPage.js
> [OGUI-600] Remove center alignment

- Control/public/workflow/Workflow.js
- Control/public/workflow/workflowsPage.js
- Control/test/public/page-new-environment-mocha.js
> [OGUI-610] trim user input new env

- Control/test/integration/control-environment.js
- Control/test/integration/create-new-environment.js
> [OGUI-608] Add waiting time after request ends

- Framework/Backend/index.js
- Framework/Backend/services/jira.js
- Framework/Backend/test/mocha-jira.js
- Framework/README.md
- Framework/docs/guide/jira.md
> [OGUI-421] Add JIRA service to framework

- Control/package-lock.json
- Control/package.json
- Control/public/workflow/Workflow.js
- Control/public/workflow/revisionPanel.js
> [OGUI-626] Improve revision panel

- QualityControl/public/object/objectPropertiesSidebar.js
> [OGUI-634] Add drawing option as text

- QualityControl/public/layout/Layout.js
- QualityControl/public/layout/layoutShowPage.js
- QualityControl/public/object/QCObject.js
- QualityControl/public/object/objectTreePage.js
- QualityControl/public/object/objectTreeSidebar.js
- QualityControl/public/object/view/objectViewPage.js
- QualityControl/test/public/mocha-index.js
PR based on user's feedback:
* Layout view should have an option in EDIT mode to show/hide the timestamps under plots. This should be saved against the layout profile and be applicable to all tabs
* Object View should display the last modified timestamp under the name 
* Object Tree View should display the last modified timestamp under the plot
> [OGUI-635] Add timestamp view to objects' plot

- QualityControl/tobject2json.cc
> Use new, simpler, API (QC-368)

- QualityControl/lib/QCModel.js
- QualityControl/lib/QCModelDemo.js
- QualityControl/lib/api.js
- QualityControl/lib/connector/LayoutConnector.js
- QualityControl/package-lock.json
- QualityControl/package.json
- QualityControl/test/lib/mocha-layout-connector.js
Extract layout code in a separate connector for the purpose of:
* improve maintainability and add tests;
* prepare for migration to SQLite for users profiles
> [OGUI-641] add layout connector

- Control/test/integration/control-environment.js
- Control/test/integration/create-new-environment.js
Test steps now will include the name of the workflow that is being controlled. 
For the step creating the environment, revision will be included as well in case of failure.
> [OGUI-643] Improve test steps name
